---
abstract: 'Simple utility module to make the easy to use IPC::Run3 even more easy to use.'
author:
  - 'Alan Young <harleypig@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::CheckDeps: 0
  Test::More: 0.94
  Test::Requires: 0
  Test::UseAllModules: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300007, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Run3-Simple
no_index:
  directory:
    - t
    - xt
requires:
  Carp: 0
  Exporter: 0
  IPC::Run3: 0
  strict: 0
  warnings: 0
resources: {}
version: 0.004
